name: 'sync repos'
description: 'push to remote develop'
inputs:
  source-repo: 
    required: true
  target-repo:
    required: true
runs:
  using: "composite"
  steps:
      - run: |
            git config user.name givinkwon
            git config user.email rlqls505@naver.com
            git checkout develop
            git remote add service https://givinkwon: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@github.com/boltnnut-platform-test
            git push service --force
        shell: bash
