name: 'sync repos'
description: 'get pull from upstream master and push to origin master'
inputs:
  source-repo: 
    required: true
  target-repo:
    required: true
runs:
  using: "composite"
  steps:
      - run: |
            git config user.name givinkwon
            git config user.email rlqls505@naver.com
            git checkout develop
            git remote add service ${{ inputs.target-repo }} 
            git push service --force
        shell: bash
