name: 'sync repos'
description: 'get pull from upstream master and push to origin master'
inputs:
  source-repo: 
    required: true
  target-repo:
    required: true
runs:
  using: "composite"
  steps:
      - run: |
            git config user.name givinkwon
            git config user.email rlqls505@naver.com
            git checkout develop
            git remote add service ${{ inputs.source-repo }} 
            git fetch service
            git config pull.rebase false 
            git pull service develop --force 
            git push origin develop
        shell: bash
